#!/usr/bin python3
#this script be a tool for documenting your cursor position
import pyautogui as pg
def mouse_track(name, buffer= []):
  string = input("note cursor position: ")
  if string == "q"
    return name, buffer
  else:
    sequence = name + " " + string + buffer
    buffer.append(sequence)
    return mouse_track(name)

print(mouse_track('toad'))
